version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news-aggregator-app
        env_file:
            - .env
        ports:
            - 5000:5000
        depends_on:
            - db
            - redis

    db:
        image: postgres
        restart: always
        container_name: news-aggregator-db
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - '5432:5432'

    redis:
        image: redis
        container_name: news-aggregator-redis-cache
        ports:
            - '6379:6379'

volumes:
    db-data:
