version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news-aggregator-app
        env_file:
            - .env
        ports:
            - 5000:5000
        depends_on:
            - db
            - redis
            - rabbitmq
            - elasticsearch

    db:
        image: postgres
        restart: always
        container_name: news-aggregator-db
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - '5432:5432'

    redis:
        image: redis
        container_name: news-aggregator-redis-cache
        ports:
            - '6379:6379'

    rabbitmq:
        image: rabbitmq:3-management
        container_name: news-aggregator-rabbitmq
        ports:
            - '5672:5672' # for RabbitMQ
            - '15672:15672' # for RabbitMQ management UI

    elasticsearch:
        image: elasticsearch:7.17.23
        container_name: news-aggregator-elasticsearch
        environment:
            - discovery.type=single-node
        volumes:
            - es-data:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'

volumes:
    db-data:
    es-data:
